CREATE DATABASE ProjetoJoseph;

USE ProjetoJoseph;

CREATE TABLE Plano(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL
);

CREATE TABLE Aluno(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    IdPlano INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Cpf VARCHAR(255) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
    Telefone VARCHAR(255) NOT NULL,
    Senha VARCHAR(255) NOT NULL
);

ALTER TABLE Aluno
ADD CONSTRAINT FK_IdPlano FOREIGN KEY (IdPlano) REFERENCES Plano(Id);

CREATE TABLE Professor(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Cpf VARCHAR(255) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
    Telefone VARCHAR(255) NOT NULL,
    Senha VARCHAR(255) NOT NULL
);

CREATE TABLE Treino(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    IdAluno INT NOT NULL,
    IdProfessor INT NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
    Descricao TEXT NOT NULL,
    DataCriacao DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Treino
ADD CONSTRAINT FK_IdAluno FOREIGN KEY (IdAluno) REFERENCES Aluno(Id),
ADD CONSTRAINT FK_IdProfessor FOREIGN KEY (IdProfessor) REFERENCES Professor(Id);

INSERT INTO Plano (Nome) VALUES 
('Plano Mensal'),
('Plano Trimestral'),
('Plano Semestral'),
('Plano Anual');

SELECT	* FROM Plano;
